[package]
name = "evil_hangman"
version = "0.1.0"
authors = ["Jacob McKenney <91638338+jacobmckenney@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
